### ISSUE TITLE
Getting lldb - ghidra setup working: Program unavailable

### ISSUE THREAD

**Issue by dvcrn** [bootleg/ret-sync#42]
Hi, thanks for this great plugin! 

I am trying to get lldb setup with either ghidra or IDA Pro (don't assume you want to make a Hopper plugin, do you? :))

I setup lldb to load the extension and can start the sync which then gives me a debug message:

```
[*] retsync init
[>] server started
[x] fail to parse json request: org.json.JSONException: JSONObject["dialect"] not found.
<< {"msg": "dbg connect - Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64", "type": "new_dbg"}
[x] program unavailable: <myprogram>
```

I tried this with a IDA Pro installation and it's working really well, just with ghidra it can't manage to find the program for some reason. Same setup as in IDA

The binary I am trying to load is a loader program for a library that I want to debug. I double-checked that process name is identical 

Tried both, self-built and the extension from the dist/ that was already there but same behaviour

**Comment by bootleg** [comment]
Hi @dvcrn 


> I am trying to get lldb setup with either ghidra or IDA Pro (don't assume you want to make a Hopper plugin, do you? :))

That's correct :) I have not had the occasion to use it so far.

I pushed a fix regarding the missing dialect information. That may be a part of the problem.

I'll investigate further the behavior (program not found). I did a quick check running lldb in Ubuntu/WSL; there was other issues however I'm really unfamiliar with this debugger.

**Comment by bootleg** [comment]
With further testing and upgrading the vm from WSL1 to WSL2, syncing seems to work correctly. Still got some dysfunctions from the API though.

**Comment by dvcrn** [comment]
Thanks for getting at this so fast! I tried the current HEAD but am still getting the same errors. Anything I can provide for debugging this?

**Comment by bootleg** [comment]
Yes, if you can provide me the error messages that you receive. Are they still the same is in your first post ?

At least I'd hope the exception would not occur anymore:

> [x] fail to parse json request: org.json.JSONException: JSONObject["dialect"] not found.

So your setup works fine with IDA but is not working with Ghidra. You have an idb/ghidra project that contains the lib you want to debug ? Is that correct ?

I did the testing one my side with lldb-10 and lldb-6 (from Ubuntu though).

**Comment by bootleg** [comment]
I'm closing the issue due to its inactivity. I believe the MacOS LLDB plugin is functional right now. 
Please re-open if necessary.
